[project]
channels = ["conda-forge"]
description = "Modeling of protein C1orf94"
name = "protein_modeling"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pdbfixer = ">=1.10,<2"
vermouth = ">=0.12.0,<0.13"
